# Generated by Django 5.1.7 on 2026-04-12 15:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BasePokemon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pokeapi_id",
                    models.PositiveIntegerField(blank=True, null=True, unique=True),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("base_hp", models.PositiveSmallIntegerField()),
                ("base_attack", models.PositiveSmallIntegerField()),
                ("base_defense", models.PositiveSmallIntegerField()),
                ("base_sp_attack", models.PositiveSmallIntegerField()),
                ("base_sp_defense", models.PositiveSmallIntegerField()),
                ("base_speed", models.PositiveSmallIntegerField()),
            ],
            options={
                "ordering": ["pokeapi_id", "name"],
            },
        ),
        migrations.CreateModel(
            name="PokemonType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Move",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pokeapi_id",
                    models.PositiveIntegerField(blank=True, null=True, unique=True),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("power", models.PositiveSmallIntegerField()),
                (
                    "learnable_by",
                    models.ManyToManyField(
                        blank=True,
                        related_name="learnable_moves",
                        to="pokedex.basepokemon",
                    ),
                ),
                (
                    "move_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="moves",
                        to="pokedex.pokemontype",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MyPokemon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nickname", models.CharField(blank=True, max_length=100)),
                (
                    "level",
                    models.PositiveSmallIntegerField(
                        default=50,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("hp_max", models.PositiveSmallIntegerField(editable=False)),
                ("hp_current", models.PositiveSmallIntegerField(editable=False)),
                ("attack", models.PositiveSmallIntegerField(editable=False)),
                ("defense", models.PositiveSmallIntegerField(editable=False)),
                ("sp_attack", models.PositiveSmallIntegerField(editable=False)),
                ("sp_defense", models.PositiveSmallIntegerField(editable=False)),
                ("speed", models.PositiveSmallIntegerField(editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "base_pokemon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="instances",
                        to="pokedex.basepokemon",
                    ),
                ),
                (
                    "moves",
                    models.ManyToManyField(
                        blank=True, related_name="pokemon_instances", to="pokedex.move"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="basepokemon",
            name="type_primary",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="primary_pokemon",
                to="pokedex.pokemontype",
            ),
        ),
        migrations.AddField(
            model_name="basepokemon",
            name="type_secondary",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="secondary_pokemon",
                to="pokedex.pokemontype",
            ),
        ),
        migrations.CreateModel(
            name="TypeEffectiveness",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("multiplier", models.DecimalField(decimal_places=1, max_digits=3)),
                (
                    "attacking_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attacking_matchups",
                        to="pokedex.pokemontype",
                    ),
                ),
                (
                    "defending_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="defending_matchups",
                        to="pokedex.pokemontype",
                    ),
                ),
            ],
            options={
                "unique_together": {("attacking_type", "defending_type")},
            },
        ),
    ]
