# Generated by Django 5.1.7 on 2026-04-12 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pokedex", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Battle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("ongoing", "En curso"), ("finished", "Terminada")],
                        default="ongoing",
                        max_length=10,
                    ),
                ),
                ("current_turn", models.PositiveSmallIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "pokemon_1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="battles_as_p1",
                        to="pokedex.mypokemon",
                    ),
                ),
                (
                    "pokemon_2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="battles_as_p2",
                        to="pokedex.mypokemon",
                    ),
                ),
                (
                    "winner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="battles_won",
                        to="pokedex.mypokemon",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Turn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("turn_number", models.PositiveSmallIntegerField()),
                ("damage_dealt", models.PositiveSmallIntegerField()),
                ("effectiveness", models.DecimalField(decimal_places=1, max_digits=3)),
                ("random_factor", models.PositiveSmallIntegerField()),
                ("defender_hp_before", models.PositiveSmallIntegerField()),
                ("defender_hp_after", models.SmallIntegerField()),
                (
                    "attacker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="turns_as_attacker",
                        to="pokedex.mypokemon",
                    ),
                ),
                (
                    "battle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="turns",
                        to="battle.battle",
                    ),
                ),
                (
                    "defender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="turns_as_defender",
                        to="pokedex.mypokemon",
                    ),
                ),
                (
                    "move_used",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="pokedex.move"
                    ),
                ),
            ],
            options={
                "ordering": ["battle", "turn_number"],
                "unique_together": {("battle", "turn_number")},
            },
        ),
    ]
